Development maharta
karuniasentosa/berikan pull request #1
Opened 2021-11-30 01:54 UTC by Gdcr7

halo, tolong di review mas, klo ada yang kurang jangan enggan buat ngasi saran

2021-11-30 04:51 UTC, karuniasentosa requested changes
Good job, mas Maharta. Progress kita bisa jadi lebih cepat. Namun aku ada beberapa saran supaya kodingan kita bisa lebih gampang dibaca dan lebih enak dilihat tampilannya. Ada beberapa kode yang aku review dan ini kesimpulannya:  
1. Design yang udah kita buat di Figma adalah design yang kasar. Jadi seperti ukuran tulisan button adalah ukuran kasar. Mas @Gdcr7  bisa modifikasi lagi di implementasinya biar jadi lebih enak dilihat.
1. Halaman home, login, signup_continue itu sebenarnya harus masuk ke dalam satu halaman, jadi tidak ada scrolling yang diperlukan oleh klien.

Cukup sekian, ada beberapa changes yang aku sarankan

2021-11-30 04:51 UTC, karuniasentosa commented on lib/widget/custom_textfield.dart
> +}
Pakai [`TextField`](https://api.flutter.dev/flutter/material/TextField-class.html) yang sudah tersedia di Flutter aja.

2021-11-30 04:51 UTC, karuniasentosa commented on lib/widget/button/black_button.dart
> +          child: Text(
Daripada menggunakan `Align` dan `SizedBox` kita bisa memanfaatkan `Padding` di dalam `ElevatedButton`, kemudian  taruh `Text` di dalam `Padding` tersebut.  
Sekali lagi, design dalam Figma hanyalah design kasar.  Mas  @Gdcr7  bisa ubah implementasinya agar terlihat lebih enak.
```suggestion
    return ElevatedButton(
      onPressed: onPressed,
      child: Padding(
        padding: EdgeInsets.symmetric(vertical: 16.0),
        child: Text(
```

2021-11-30 06:41 UTC, Gdcr7 commented on lib/widget/button/black_button.dart
> +class BlackButton extends StatelessWidget {
Okeh, ini aku refactor sekarang juga

2021-11-30 06:41 UTC, Gdcr7 commented on lib/ui/home_page.dart
> +        body: ListView(
ini diskusi di discord ya mas @karuniasentosa

2021-11-30 06:45 UTC, Gdcr7 commented on lib/widget/button/kembali_button.dart
> +}
Okeh mas, aku lupa ada textbutton yang tulisannya "tentang kami" , dan "lupa password", aku nanti buat jadi lebih umum lagi.

2021-11-30 06:46 UTC, Gdcr7 commented on lib/widget/custom_textfield.dart
> +}
Widget ini aku buat biar kodenya lebih gampang dibaca sih, trus tinggal isi hintnya aja karena textfieldnya sama semua, cuma beda di hint, gimana mas? klo pake TextField di setiap page yang ada kodingannya bakal jauh lebih banyak di tiap page.

2021-11-30 06:47 UTC, Gdcr7 commented on lib/widget/button/black_button.dart
> +          child: Text(
oke, layoutnya akan ku adjust sekarang

2021-12-07 06:38 UTC, karuniasentosa commented
Looks good to me!

2021-12-07 06:38 UTC, merged